//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPaimon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPaimon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free and open source..
        /// </summary>
        internal static string AboutDesc1 {
            get {
                return ResourceManager.GetString("AboutDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you encounter any problems or have a suggestion
        ///Go ahead and submit an issue at.
        /// </summary>
        internal static string AboutDesc2 {
            get {
                return ResourceManager.GetString("AboutDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        internal static string AboveNormal {
            get {
                return ResourceManager.GetString("AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Close.
        /// </summary>
        internal static string AutoClose {
            get {
                return ResourceManager.GetString("AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game Automatically.
        /// </summary>
        internal static string AutoStartGame {
            get {
                return ResourceManager.GetString("AutoStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        internal static string BelowNormal {
            get {
                return ResourceManager.GetString("BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Window.
        /// </summary>
        internal static string BorderlessWindow {
            get {
                return ResourceManager.GetString("BorderlessWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Path.
        /// </summary>
        internal static string CurrentPath {
            get {
                return ResourceManager.GetString("CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Resolution.
        /// </summary>
        internal static string CustomResolution {
            get {
                return ResourceManager.GetString("CustomResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLLs will be injected in the order of this list.
        /// </summary>
        internal static string DLLLabelDescription {
            get {
                return ResourceManager.GetString("DLLLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLLs.
        /// </summary>
        internal static string DLLs {
            get {
                return ResourceManager.GetString("DLLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen Mode.
        /// </summary>
        internal static string FullscreenMode {
            get {
                return ResourceManager.GetString("FullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} installation of the game.
        /// </summary>
        internal static string GameFoundLabel {
            get {
                return ResourceManager.GetString("GameFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Options.
        /// </summary>
        internal static string LaunchOptions {
            get {
                return ResourceManager.GetString("LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor:.
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Saving.
        /// </summary>
        internal static string PowerSaving {
            get {
                return ResourceManager.GetString("PowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Priority:.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realtime.
        /// </summary>
        internal static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectPath {
            get {
                return ResourceManager.GetString("SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your game is not listed above, you can either:
        ///1. Open the game now and the PowerPaimon will try to find it&apos;s location
        ///2. Use the browse button below.
        /// </summary>
        internal static string SetupHint {
            get {
                return ResourceManager.GetString("SetupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        internal static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuspendLoad.
        /// </summary>
        internal static string SuspendLoad {
            get {
                return ResourceManager.GetString("SuspendLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        internal static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPaimon will exit upon game closing.
        /// </summary>
        internal static string TTAutoClose {
            get {
                return ResourceManager.GetString("TTAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will take effect on subsequent launch.
        /// </summary>
        internal static string TTAutoStart {
            get {
                return ResourceManager.GetString("TTAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerPaimon will minimized to tray on starup.
        /// </summary>
        internal static string TTMinimized {
            get {
                return ResourceManager.GetString("TTMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets fps to 10 and low process priority upon losing focus (e.g. tabbing out of game).
        /// </summary>
        internal static string TTPowerSave {
            get {
                return ResourceManager.GetString("TTPowerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This can ensure dll gets loaded before the game starts
        ///It may not work all the times
        ///Uncheck this if the game crashes.
        /// </summary>
        internal static string TTSuspendLoad {
            get {
                return ResourceManager.GetString("TTSuspendLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Mobile UI.
        /// </summary>
        internal static string UseMobileUI {
            get {
                return ResourceManager.GetString("UseMobileUI", resourceCulture);
            }
        }
    }
}
