//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPaimon.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerPaimon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This program is free and open source. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDesc1 {
            get {
                return ResourceManager.GetString("AboutDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you encounter any problems or have a suggestion
        ///Go ahead and submit an issue at に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDesc2 {
            get {
                return ResourceManager.GetString("AboutDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Above normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboveNormal {
            get {
                return ResourceManager.GetString("AboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoClose {
            get {
                return ResourceManager.GetString("AutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Game Automatically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoStartGame {
            get {
                return ResourceManager.GetString("AutoStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Below normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BelowNormal {
            get {
                return ResourceManager.GetString("BelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borderless Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BorderlessWindow {
            get {
                return ResourceManager.GetString("BorderlessWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentPath {
            get {
                return ResourceManager.GetString("CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomResolution {
            get {
                return ResourceManager.GetString("CustomResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DLLs will be injected in the order of this list に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DLLLabelDescription {
            get {
                return ResourceManager.GetString("DLLLabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DLLs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DLLs {
            get {
                return ResourceManager.GetString("DLLs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fullscreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fullscreen Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullscreenMode {
            get {
                return ResourceManager.GetString("FullscreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Found!
        ///{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameDetectedLabel {
            get {
                return ResourceManager.GetString("GameDetectedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found {0} installation of the game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GameFoundLabel {
            get {
                return ResourceManager.GetString("GameFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable HDR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Hdr {
            get {
                return ResourceManager.GetString("Hdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LaunchOptions {
            get {
                return ResourceManager.GetString("LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitor: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Monitor {
            get {
                return ResourceManager.GetString("Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An instance of the game is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgAlreadyGameLaunched {
            get {
                return ResourceManager.GetString("MsgAlreadyGameLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to enable HDR: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgEnableHdrFailed {
            get {
                return ResourceManager.GetString("MsgEnableHdrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game path is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgInvalidPath {
            get {
                return ResourceManager.GetString("MsgInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimized to tray に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NBMinimized {
            get {
                return ResourceManager.GetString("NBMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A new version is available!
        ///
        ///Current version: {0}
        ///Latest version: {1}
        ///
        ///Would you like to go to the release page? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionNotifyLabel {
            get {
                return ResourceManager.GetString("NewVersionNotifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Saving に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerSaving {
            get {
                return ResourceManager.GetString("PowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process Priority: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Realtime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Realtime {
            get {
                return ResourceManager.GetString("Realtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resolution: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectPath {
            get {
                return ResourceManager.GetString("SelectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If your game is not listed above, you can either:
        ///1. Open the game now and the PowerPaimon will try to find it&apos;s location
        ///2. Use the browse button below に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupHint {
            get {
                return ResourceManager.GetString("SetupHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Minimized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartMinimized {
            get {
                return ResourceManager.GetString("StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SuspendLoad に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SuspendLoad {
            get {
                return ResourceManager.GetString("SuspendLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PowerPaimon will exit upon game closing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTAutoClose {
            get {
                return ResourceManager.GetString("TTAutoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This will take effect on subsequent launch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTAutoStart {
            get {
                return ResourceManager.GetString("TTAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PowerPaimon will minimized to tray on starup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTMinimized {
            get {
                return ResourceManager.GetString("TTMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets fps to 10 upon losing focus (e.g. tabbing out of game) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTPowerSave {
            get {
                return ResourceManager.GetString("TTPowerSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This can ensure dll gets loaded before the game starts
        ///It may not work all the times
        ///Uncheck this if the game crashes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TTSuspendLoad {
            get {
                return ResourceManager.GetString("TTSuspendLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use Mobile UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseMobileUI {
            get {
                return ResourceManager.GetString("UseMobileUI", resourceCulture);
            }
        }
    }
}
